server:
  port: 8081

jwt:
  secret: YXNkc2Fkc2Fkc2Fka2JzYWpoZHZoYWxzZmFzZnNmc2RmYWZk
  lifetime: 20m

spring:

  session:
    jdbc:
      initialize-schema: always


  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: root
    username: acheron
    driver-class-name: org.postgresql.Driver


